name: Autofix Formatting

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run formatter autofix
        run: npm run format

      - name: Commit formatting changes
        uses: autofix-ci/action@v1
        with:
          commit-message: 'style(tooling): autofix formatting'
